// Łatka: polskie napisy w @anionex/dsh-turn-rewind (plugin ma chińskie literały na sztywno, bez i18n).
// Podmiana tekstu w bundlu klienta, najdłuższe frazy najpierw; fragmenty szablonów `${…}` zostają nietknięte.
// Użycie: node rewind-polish.mjs <node_modules>   (idempotentna; brak frazy = błąd, bo upstream się zmienił)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const file = join(process.argv[2], '@anionex/dsh-turn-rewind/lib/client.js');
if (!existsSync(file)) { console.log('rewind-polish: brak dsh-turn-rewind, pomijam'); process.exit(0); }
let s = readFileSync(file, 'utf8');
if (s.includes('[android] rewind polish')) { console.log('rewind-polish: już nałożona'); process.exit(0); }

const MAP = [
  ['项目文件在展开列表时发生了变化。', 'Pliki projektu zmieniły się podczas rozwijania listy.'],
  ['无法读取完整的文件列表。', 'Nie udało się odczytać pełnej listy plików.'],
  ['服务器返回了不匹配的回退模式：', 'Serwer zwrócił niezgodny tryb cofania: '],
  ['已创建从这里开始的新对话；项目文件保持不变。', 'Utworzono nową rozmowę od tego miejsca; pliki projektu bez zmian.'],
  ['新对话已创建，但没能自动打开：', 'Nowa rozmowa utworzona, ale nie udało się jej otworzyć automatycznie: '],
  ['项目文件已恢复；当前对话保持不变。恢复前的文件已自动备份。', 'Pliki projektu przywrócone; bieżąca rozmowa bez zmian. Stan sprzed przywrócenia został automatycznie zarchiwizowany.'],
  ['项目文件已恢复，并已创建新对话。恢复前的文件已自动备份。', 'Pliki projektu przywrócone i utworzono nową rozmowę. Stan sprzed przywrócenia został automatycznie zarchiwizowany.'],
  ['文件已经恢复，新对话也已创建，但没能自动打开：', 'Pliki przywrócone i nowa rozmowa utworzona, ale nie udało się jej otworzyć automatycznie: '],
  ['恢复并从这里继续', 'Przywróć i kontynuuj od tego miejsca'],
  ['恢复到发送这条消息之前', 'Cofnij do stanu sprzed tej wiadomości'],
  ['查看恢复的文件，选择适合你的回退方式。当前会话不受影响。', 'Przejrzyj przywracane pliki i wybierz sposób cofnięcia. Bieżąca sesja nie zostanie naruszona.'],
  ['正在恢复…', 'Przywracanie…'],
  ['正在检查可以恢复的项目文件…', 'Sprawdzanie plików projektu możliwych do przywrócenia…'],
  ['这条消息发送前的文件还在保存，请稍后再试。', 'Pliki sprzed tej wiadomości są jeszcze zapisywane, spróbuj za chwilę.'],
  ['没有保存这条消息发送前的文件。可能是当时还没启用回退功能、记录已超过保留期限，或已关闭自动检查点。仍可只回溯消息。', 'Brak zapisanych plików sprzed tej wiadomości. Możliwe, że cofanie nie było wtedy włączone, zapis wygasł albo automatyczne punkty kontrolne są wyłączone. Nadal możesz cofnąć same wiadomości.'],
  ['恢复文件并从这里继续', 'Przywróć pliki i kontynuuj od tego miejsca'],
  ['创建一个从这里开始的新会话（当前对话会保留）', 'Tworzy nową sesję od tego miejsca (bieżąca rozmowa zostaje)'],
  ['只恢复文件', 'Tylko przywróć pliki'],
  ['恢复这条消息发送前的文件，当前对话保持不变。', 'Przywraca pliki sprzed tej wiadomości, bieżąca rozmowa bez zmian.'],
  ['只回溯消息（不动文件）', 'Tylko cofnij wiadomości (bez plików)'],
  ['创建一个从这里开始的新会话，项目文件保持当前状态。', 'Tworzy nową sesję od tego miejsca, pliki projektu zostają w obecnym stanie.'],
  ['项目文件保持不变', 'Pliki projektu bez zmian'],
  ['恢复后在新对话里继续', 'Po przywróceniu kontynuuj w nowej rozmowie'],
  ['当前对话保持不变', 'Bieżąca rozmowa bez zmian'],
  ['仅创建从这里继续的新对话', 'Tylko utwórz nową rozmowę od tego miejsca'],
  ['这个项目目录还有别的对话正在运行。恢复文件会影响到它们，因此本次操作已被阻止。请等那些对话结束或停止后，再重新检查。', 'W tym katalogu projektu działają inne rozmowy. Przywrócenie plików wpłynęłoby na nie, więc operacja została zablokowana. Poczekaj, aż się zakończą lub zatrzymają, i sprawdź ponownie.'],
  ['当前所在的 Git 分支和发送这条消息时不同。恢复不会切换分支，只会把当时的文件内容恢复到当前分支。', 'Bieżąca gałąź Git jest inna niż w chwili wysłania tej wiadomości. Przywrócenie nie przełączy gałęzi, tylko odtworzy ówczesną zawartość plików na bieżącej gałęzi.'],
  ['这条消息之后有了新的 Git 提交。恢复只会改文件，不会撤销提交；完成后这些文件会显示为未提交修改。', 'Po tej wiadomości pojawiły się nowe commity Git. Przywrócenie zmienia tylko pliki, nie cofa commitów; po zakończeniu pliki będą widoczne jako niezacommitowane zmiany.'],
  ['Git 正在进行合并、变基或类似操作。请先完成或取消这次 Git 操作，再重新检查。', 'Git jest w trakcie scalania, rebase albo podobnej operacji. Najpierw dokończ lub anuluj tę operację, potem sprawdź ponownie.'],
  ['恢复信息已经失效，请重新检查。', 'Dane przywracania wygasły, sprawdź ponownie.'],
  ['项目文件在检查后又发生了变化。为避免覆盖新修改，这次恢复已失效，请重新检查。', 'Pliki projektu zmieniły się po sprawdzeniu. Żeby nie nadpisać nowych zmian, to przywrócenie wygasło; sprawdź ponownie.'],
  ['项目文件已经是这条消息发送前的状态，无需恢复文件。可选择「只回溯消息」重新开始这段对话。', 'Pliki projektu są już w stanie sprzed tej wiadomości, nie trzeba ich przywracać. Wybierz „Tylko cofnij wiadomości”, żeby zacząć tę rozmowę od nowa.'],
  ['正在读取全部文件…', 'Odczyt wszystkich plików…'],
  ['查看全部 ', 'Pokaż wszystkie '],
  ['恢复前会自动备份当前文件；若恢复失败会自动还原，项目不会停留在只恢复了一部分的状态。', 'Przed przywróceniem bieżące pliki są automatycznie archiwizowane; jeśli przywracanie się nie uda, stan wraca sam, projekt nie zostanie w połowie przywrócony.'],
  ['重新检查', 'Sprawdź ponownie'],
  ['用户/救援恢复点上限', 'Limit punktów użytkownika i ratunkowych'],
  ['每个工作区保留的最大手动与救援恢复点数量', 'Maksymalna liczba ręcznych i ratunkowych punktów przywracania na obszar roboczy'],
  ['轮次检查点上限', 'Limit punktów kontrolnych tur'],
  ['每个会话保留的最大自动轮次检查点数量（最旧的先清理）', 'Maksymalna liczba automatycznych punktów kontrolnych tur na sesję (najstarsze usuwane pierwsze)'],
  ['单恢复点文件数上限', 'Limit plików w punkcie przywracania'],
  ['一个恢复点最多纳入的文件数量', 'Maksymalna liczba plików w jednym punkcie przywracania'],
  ['单文件大小上限', 'Limit rozmiaru pliku'],
  ['读取单个普通文件的最大字节数', 'Maksymalna liczba bajtów odczytywana z jednego zwykłego pliku'],
  ['快照总量上限', 'Limit łącznego rozmiaru migawki'],
  ['单个恢复点读取的最大字节总量', 'Maksymalna łączna liczba bajtów odczytywana dla jednego punktu przywracania'],
  ['恢复计划有效期（毫秒）', 'Ważność planu przywracania (ms)'],
  ['回溯计划从创建到失效的时间', 'Czas od utworzenia planu cofania do jego wygaśnięcia'],
  ['锁回收时长（毫秒）', 'Czas odzyskania blokady (ms)'],
  ['锁属主消失多久后允许回收该锁', 'Po jakim czasie od zniknięcia właściciela blokady można ją odzyskać'],
  ['检查点超时（毫秒）', 'Limit czasu punktu kontrolnego (ms)'],
  ['单次自动检查点最多阻塞消息发送的时间，超时记录跳过', 'Jak długo automatyczny punkt kontrolny może wstrzymać wysłanie wiadomości; po przekroczeniu jest pomijany'],
  ['检查点读取上限', 'Limit odczytu punktu kontrolnego'],
  ['单次 Git 原生检查点最多读取的未缓存字节数', 'Maksymalna liczba niebuforowanych bajtów odczytywana przez natywny punkt kontrolny Git'],
  ['关闭（不创建文件检查点）', 'Wyłączone (bez punktów kontrolnych plików)'],
  ['自动（推荐）', 'Automatycznie (zalecane)'],
  ['Git 原生（大仓库）', 'Natywny Git (duże repozytoria)'],
  ['完整快照（兼容模式）', 'Pełna migawka (tryb zgodności)'],
  [' 必须是正整数。', ' musi być dodatnią liczbą całkowitą.'],
  ['Turn Rewind 回退设置', 'Ustawienia cofania tur'],
  ['自动文件检查点、信任策略与检查点保留上限；回退按钮在各条用户消息上', 'Automatyczne punkty kontrolne plików, polityka zaufania i limity; przycisk cofania jest przy każdej wiadomości użytkownika'],
  ['自动文件检查点', 'Automatyczne punkty kontrolne plików'],
  ['正在加载设置…', 'Wczytywanie ustawień…'],
  ['当前部署未提供设置服务，以下选项不可用。', 'To wdrożenie nie udostępnia usługi ustawień, poniższe opcje są niedostępne.'],
  ['设置为只读（当前浏览器进程内保存），修改不可用。', 'Ustawienia tylko do odczytu (zapis w bieżącym procesie przeglądarki), zmiany niedostępne.'],
  ['关闭后不再为每条消息保存文件检查点；回退弹窗仍可只回溯消息', 'Po wyłączeniu punkty kontrolne plików nie są zapisywane dla wiadomości; okno cofania nadal pozwala cofnąć same wiadomości'],
  ['恢复默认', 'Przywróć domyślne'],
  ['检查点信任策略', 'Polityka zaufania punktów kontrolnych'],
  ['快速信任 Git/stat 元数据；严格会逐一重读文件内容', 'Szybka ufa metadanym Git/stat; ścisła czyta ponownie zawartość każdego pliku'],
  ['存储目录（在 cordis.patch.yml 中配置，不可在线修改）：', 'Katalog przechowywania (konfigurowany w cordis.patch.yml, bez zmiany na żywo): '],
  ['检查点管理', 'Zarządzanie punktami kontrolnymi'],
  ['正在刷新…', 'Odświeżanie…'],
  ['正在清理…', 'Czyszczenie…'],
  ['确认清空全部', 'Potwierdź wyczyszczenie wszystkiego'],
  ['一键清空全部', 'Wyczyść wszystko'],
  ['正在读取检查点占用…', 'Odczyt zajętości punktów kontrolnych…'],
  [' 个工作区，', ' obszarów roboczych, '],
  [' 个检查点，约 ', ' punktów kontrolnych, ok. '],
  ['（Git 原生检查点的实际磁盘占用以 Git 回收为准）。', ' (rzeczywiste zużycie dysku przez natywne punkty Git zależy od odśmiecania Git).'],
  [' 个检查点 · ', ' punktów kontrolnych · '],
  [' 个恢复待处理', ' przywróceń w toku'],
  ['清空此项目', 'Wyczyść ten projekt'],
  ['正在删除…', 'Usuwanie…'],
  ['还没有任何已保存的检查点。', 'Nie ma jeszcze żadnych zapisanych punktów kontrolnych.'],
  ['管理数据缺少 workspaces', 'W danych zarządzania brakuje workspaces'],
  ['管理数据缺少 restorePoints', 'W danych zarządzania brakuje restorePoints'],
  ['清理结果缺少 reports', 'W wyniku czyszczenia brakuje reports'],
  [' 个受保护检查点未删除', ' chronionych punktów nie usunięto'],
  [' 个删除失败', ' nie udało się usunąć'],
  ['已删除 ', 'Usunięto '],
  ['共 ', 'Łącznie '],
  ['，', ', '],
  [' 个检查点', ' punktów kontrolnych'],
  ['未知回退状态：', 'Nieznany stan cofania: '],
  ['回退预览缺少 changes', 'W podglądzie cofania brakuje changes'],
  ['回退预览缺少 activeSessionIds', 'W podglądzie cofania brakuje activeSessionIds'],
  ['新对话还没有准备好', 'Nowa rozmowa nie jest jeszcze gotowa'],
  ['回退服务返回了无法解析的内容（HTTP ', 'Usługa cofania zwróciła treść, której nie da się odczytać (HTTP '],
  ['请求失败：', 'Żądanie nie powiodło się: '],
  ['回退服务返回了空响应。', 'Usługa cofania zwróciła pustą odpowiedź.'],
  ['服务器返回了无效对象', 'Serwer zwrócił nieprawidłowy obiekt'],
  [' 无效', ' jest nieprawidłowe'],
  ['移除后来新增的文件', 'Usunie plik dodany później'],
  ['找回文件', 'Odzyska plik'],
  ['恢复之前的版本', 'Przywróci wcześniejszą wersję'],
  ['恢复文件权限', 'Przywróci uprawnienia pliku'],
  ['恢复之前的文件类型', 'Przywróci wcześniejszy typ pliku'],
  ['回退服务没有响应。请确认 @anionex/dsh-turn-rewind 已挂载到当前 DSH，并重启 DSH 后重试。', 'Usługa cofania nie odpowiada. Upewnij się, że @anionex/dsh-turn-rewind jest wpięty w ten DSH, zrestartuj DSH i spróbuj ponownie.'],
  ['回退服务返回了无法解析的内容。请重启 DSH 后重试。', 'Usługa cofania zwróciła treść, której nie da się odczytać. Zrestartuj DSH i spróbuj ponownie.'],
  ['项目文件在检查后又发生了变化。为避免覆盖新修改，请重新检查后再恢复。', 'Pliki projektu zmieniły się po sprawdzeniu. Żeby nie nadpisać nowych zmian, sprawdź ponownie przed przywróceniem.'],
  ['Git 状态在检查后又发生了变化，恢复已失效。请重新检查后再试。', 'Stan Git zmienił się po sprawdzeniu, przywrócenie wygasło. Sprawdź ponownie i spróbuj jeszcze raz.'],
  ['这个项目目录还有别的对话正在运行。请等那些对话结束或停止后，再重新检查。', 'W tym katalogu projektu działają inne rozmowy. Poczekaj, aż się zakończą lub zatrzymają, i sprawdź ponownie.'],
  ['另一个恢复操作正在处理这个项目目录。请等待它完成后重新检查。', 'Inna operacja przywracania pracuje na tym katalogu projektu. Poczekaj na jej zakończenie i sprawdź ponownie.'],
  ['这个项目目录已经不在原来的位置，旧的回退点无法再使用。', 'Ten katalog projektu nie jest już w pierwotnym miejscu, stare punkty cofania nie nadają się do użycia.'],
  ['这个项目目录的工作区类型变了（例如从普通目录变成了 Git 仓库）。旧的回退点不再适用，请重新发送一条消息生成新的回退点。', 'Zmienił się typ obszaru roboczego tego katalogu (np. ze zwykłego katalogu na repozytorium Git). Stare punkty cofania nie pasują; wyślij nową wiadomość, żeby utworzyć nowy punkt.'],
  ['项目的提交或分支已发生变化。为避免覆盖新改动，请重新检查后再恢复。', 'Commity lub gałąź projektu się zmieniły. Żeby nie nadpisać nowych zmian, sprawdź ponownie przed przywróceniem.'],
  ['这个项目目录已不属于原来的 Git 工作区，无法恢复。', 'Ten katalog projektu nie należy już do pierwotnego obszaru roboczego Git, nie da się przywrócić.'],
  ['Git 正在执行其他操作。请先完成或取消该操作，再重新检查。', 'Git wykonuje inną operację. Najpierw ją dokończ lub anuluj, potem sprawdź ponownie.'],
  ['没有找到对应的文件状态，可能已被清理。', 'Nie znaleziono odpowiedniego stanu plików, mógł zostać wyczyszczony.'],
  ['恢复未能完成，项目文件已自动还原到操作前的状态。', 'Przywracanie nie powiodło się, pliki projektu wróciły automatycznie do stanu sprzed operacji.'],
  ['文件已恢复，但无法创建新对话；项目文件已自动还原。', 'Pliki przywrócono, ale nie udało się utworzyć nowej rozmowy; pliki projektu wróciły automatycznie do poprzedniego stanu.'],
  ['本轮要保存的文件总量超过上限，剩下的文件没有纳入检查点。恢复时不会改动它们。', 'Łączny rozmiar plików w tej turze przekroczył limit, pozostałych plików nie ujęto w punkcie kontrolnym. Przywracanie ich nie zmieni.'],
  ['本轮文件数量超过上限，多出来的文件没有纳入检查点。恢复时不会改动它们。', 'Liczba plików w tej turze przekroczyła limit, nadmiarowych plików nie ujęto w punkcie kontrolnym. Przywracanie ich nie zmieni.'],
  ['有 ', 'Jest '],
  [' 个文件因为超过单文件大小上限或类型不受支持，没有纳入检查点', ' plików pominiętych w punkcie kontrolnym, bo przekraczają limit rozmiaru albo mają nieobsługiwany typ'],
  ['。恢复时不会改动它们。', '. Przywracanie ich nie zmieni.'],
  ['这个项目目录太大，在检查点时间上限内没保存完文件快照，所以本轮没有回退点（消息本身没有受影响）。可以在插件设置里调大「检查点时间上限」，或在目录根用 .dsh-rewindignore 排除大目录（例如 node_modules、构建产物、数据集）。仍可只回溯消息。', 'Ten katalog projektu jest za duży: migawka plików nie zdążyła się zapisać w limicie czasu, więc ta tura nie ma punktu cofania (sama wiadomość nie ucierpiała). Zwiększ „Limit czasu punktu kontrolnego” w ustawieniach pluginu albo wyklucz duże katalogi plikiem .dsh-rewindignore w katalogu głównym (np. node_modules, wyniki buildów, zbiory danych). Nadal możesz cofnąć same wiadomości.'],
  ['自动文件检查点已在设置里关闭，本轮没有回退点。仍可只回溯消息。', 'Automatyczne punkty kontrolne plików są wyłączone w ustawieniach, ta tura nie ma punktu cofania. Nadal możesz cofnąć same wiadomości.'],
  ['这一轮新增的内容超过检查点预算，没有保存文件快照。仍可只回溯消息。', 'Nowa zawartość tej tury przekroczyła budżet punktu kontrolnego, migawki plików nie zapisano. Nadal możesz cofnąć same wiadomości.'],
  ['本轮没有保存文件检查点：', 'W tej turze nie zapisano punktu kontrolnego plików: '],
  ['仍可只回溯消息。', 'Nadal możesz cofnąć same wiadomości.'],
  ['这个项目目录不是 Git 仓库，回退功能无法保存文件检查点。', 'Ten katalog projektu nie jest repozytorium Git, cofanie nie może zapisać punktu kontrolnego plików. '],
  ['无法读取这个项目目录的 Git 状态：', 'Nie udało się odczytać stanu Git tego katalogu: '],
  ['本轮有文件超过检查点的大小或数量上限，没有保存文件检查点。', 'Pliki w tej turze przekraczają limit rozmiaru lub liczby punktu kontrolnego, punktu nie zapisano. '],
  ['项目目录里有无法保存的特殊文件（如 socket、设备文件、FIFO），没有保存文件检查点。', 'W katalogu projektu są pliki specjalne, których nie da się zapisać (socket, urządzenie, FIFO), punktu kontrolnego nie zapisano. '],
  ['项目目录里的 .dsh-rewindignore 内容无效，没有保存文件检查点。修正该文件后可重新发送消息。', 'Plik .dsh-rewindignore w katalogu projektu jest nieprawidłowy, punktu kontrolnego nie zapisano. Popraw plik i wyślij wiadomość ponownie.'],
  ['项目目录里有无法安全保存的路径（例如嵌套的独立 Git 仓库），没有保存文件检查点。', 'W katalogu projektu są ścieżki, których nie da się bezpiecznie zapisać (np. zagnieżdżone osobne repozytorium Git), punktu kontrolnego nie zapisano. '],
  ['没能保存这条消息发送前的文件：', 'Nie udało się zapisać plików sprzed tej wiadomości: '],
  ['恢复文件', 'Przywróć pliki'],
  ['只回溯消息', 'Tylko cofnij wiadomości'],
  ['已完成', 'Zakończono'],
  ['已覆盖', 'Nadpisane'],
  ['将恢复 ', 'Przywróconych zostanie '],
  [' 个文件', ' plików'],
  ['快速', 'Szybka'],
  ['严格', 'Ścisła'],
  ['手动', 'Ręczny'],
  ['救援', 'Ratunkowy'],
  ['轮次', 'Tura'],
  ['展开', 'Rozwiń'],
  ['收起', 'Zwiń'],
  ['刷新', 'Odśwież'],
  ['删除', 'Usuń'],
  ['关闭', 'Zamknij'],
  ['取消', 'Anuluj'],
];
// \uXXXX w źródle (np. "将恢复 ") -> dekoduj do znaków, żeby podmiana tekstowa działała
s = s.replace(/\\u([0-9a-fA-F]{4})/g, (m, h) => { const code = parseInt(h, 16); return code >= 0x80 ? String.fromCharCode(code) : m; });   // dekoduj wszystkie nie-ASCII escape'y (także interpunkcję pełnej szerokości)
const missing = [];
for (const [zh, pl] of [...MAP].sort((a, b) => b[0].length - a[0].length)) {
  if (!s.includes(zh)) { missing.push(zh); continue; }
  s = s.split(zh).join(pl);
}
const left = (s.match(/[一-鿿]/g) || []).length;
if (missing.length > 8) throw new Error('rewind-polish: za dużo brakujących fraz (' + missing.length + ') — plugin zmienił się upstream: ' + missing.slice(0, 3).join(' | '));
s = s.replace('class RewindRequestError', '/* [android] rewind polish */ class RewindRequestError');
if (!s.includes('[android] rewind polish')) throw new Error('rewind-polish: brak markera RewindRequestError');
writeFileSync(file, s);
console.log('rewind-polish: nałożona; nieznalezione frazy: ' + missing.length + '; pozostałe znaki CJK: ' + left);
